---
AWSTemplateFormatVersion:  "2010-09-09"
Description: "This stack holds bastion setup, including ASG, SG rules"


Parameters:

  AllowedCidrRanges:
    Description: AllowedCidr used to the bastion
    Type: String
    Default: 10.63.0.0/16
  BastionSSHKeyName:
    Description: SSHkey name for the bastion box.
    Type: String
    Default: "fctestbastion"
  BastionInstanceType:
    Description: Instance type for bastion ec2 box.
    Type: String
    Default: t2.nano
  EnvironmentName:
    Description: EnvironmentName aka stack identifier
    Type: String
    Default: "dev"
  HostedZoneID:
    Description: "hosted zone id for the new sub domain"
    Type: String
  DomainName:
    Description: "domain name want to register"
    Type: String
  DockerVersion:
    Description: docker image tag
    Type: String
    Default: "latest"
  KeyName:
    Description: Application ssh login keypair name
    Type: AWS::EC2::KeyPair::KeyName
    Default: "fctest"

# assume that VPC has been created and essential values exported
Resources:

  BastionASG:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      AutoScalingGroupName: !Sub bastion.${EnvironmentName}
      AvailabilityZones:
        Fn::GetAZs:
          Ref: "AWS::Region"
      LaunchConfigurationName: !Ref BastionLaunchConfiguration
      HealthCheckType: EC2
      HealthCheckGracePeriod: 500
      DesiredCapacity: 0
      MinSize: 0
      MaxSize: 1
      Tags:
        - Key: Name
          Value: !Sub bastion.${EnvironmentName}
          PropagateAtLaunch: true
      TerminationPolicies:
        - OldestInstance
      VPCZoneIdentifier:
        Fn::Split:
          - ','
          - Fn::ImportValue:
              Fn::Sub: PublicSubnets-fctest-${EnvironmentName}

  BastionLaunchConfiguration:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Metadata:
      AWS::CloudFormation::Init:

        config:
          packages:
            yum:
              awslogs: []
          files:
            /etc/awslogs/awscli.conf:
              content: !Sub |
                [default]
                region = ${AWS::Region}
                [plugins]
                cwlogs = cwlogs
              mode: '000644'
              owner: root
              group: root
            /etc/awslogs/awscli.conf:
              content: !Sub |
                [default]
                region = ${AWS::Region}
                [plugins]
                cwlogs = cwlogs
              mode: '000644'
              owner: root
              group: root
            /etc/awslogs/awslogs.conf:
              content: !Sub |
                [general]
                state_file = /var/lib/awslogs/agent-state
                [/var/log/messages]
                datetime_format = %b %d %H:%M:%S
                file = /var/log/messages
                buffer_duration = 5000
                log_stream_name = {instance_id}/var/log/messages
                initial_position = start_of_file
                log_group_name = ${BastionLogGroup}
                [/var/log/secure]
                datetime_format = %b %d %H:%M:%S
                file = /var/log/secure
                log_stream_name = {instance_id}/var/log/secure
                log_group_name = ${BastionLogGroup}
                initial_position = start_of_file
              mode: '000644'
              owner: root
              group: root
          services:
            sysvinit:
              awslogsd:
                enabled: true
                ensureRunning: true
                packages:
                  yum:
                  - awslogs
                files:
                - '/etc/awslogs/awslogs.conf'
                - '/etc/awslogs/awscli.conf'

    Properties:
      KeyName: !Ref BastionSSHKeyName
      # ImageId: ami-00e17d1165b9dd3ec
      ImageId: ami-09b42976632b27e9b
      InstanceType: !Ref BastionInstanceType
      IamInstanceProfile: !Ref BastionProfile
      SecurityGroups:
      - !Ref BastionSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum update -y aws-cfn-bootstrap

          # Start cfn-init
          /opt/aws/bin/cfn-init -v --region ${AWS::Region} --stack ${AWS::StackName} --resource BastionLaunchConfiguration || error_exit 'Failed to run cfn-init'

          # signal success
          /opt/aws/bin/cfn-signal -e 0 --region ${AWS::Region} --stack ${AWS::StackName} --resource BastionASG

  BastionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName : !Sub bastion-${EnvironmentName}
      RetentionInDays: 7

  BastionProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: '/'
      Roles:
      - !Ref BastionIAMRole

  BastionIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'ec2.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      Path: '/'
      Policies:
      - PolicyName: logs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:Describe*
            Resource:
            - arn:aws:logs:*:*:*

  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub bastion.${EnvironmentName}
      GroupDescription: Allow traffic from office range to bastion
      VpcId:
        Fn::ImportValue:
          Fn::Sub: VpcId-fctest-${EnvironmentName}
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub ${AllowedCidrRanges}
      Tags:
        - Key: Name
          Value: !Sub bastion.${EnvironmentName}

  BastionAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub allow.bastion.access.${EnvironmentName}
      GroupDescription: Allow SSH From Bastion
      VpcId:
        Fn::ImportValue:
          Fn::Sub: VpcId-fctest-${EnvironmentName}
      Tags:
      - Key: Name
        Value: !Sub allow.bastion.access.${EnvironmentName}
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        SourceSecurityGroupId: !Ref BastionSecurityGroup

  ScheduledActionDown:
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: !Ref BastionASG
      DesiredCapacity: 0
      MinSize: 0
      MaxSize: 1
      Recurrence: "0 7 * * *"


Outputs:
  BastionAccessSecurityGroup:
    Description: Bastion Instance
    Value: !Ref BastionAccessSecurityGroup
    Export:
      Name: !Sub BastionAccessSecurityGroup-${EnvironmentName}
